// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZ52HCg8vvPcPo4AGGncy4zQ_hMZnQ8g',
    appId: '1:31364040406:web:3acd0bb8dfcc0e4eb36b77',
    messagingSenderId: '31364040406',
    projectId: 'flutter-paint-store-app',
    authDomain: 'flutter-paint-store-app.firebaseapp.com',
    storageBucket: 'flutter-paint-store-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRoZILZTfP1-77EWh-nHd6PmNbs3c9Qq4',
    appId: '1:31364040406:android:bd92e35a84c008c3b36b77',
    messagingSenderId: '31364040406',
    projectId: 'flutter-paint-store-app',
    storageBucket: 'flutter-paint-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxljftN6XnOqNEqs_qnxnmABr3c6mSqaA',
    appId: '1:31364040406:ios:1fe5b604a793bc00b36b77',
    messagingSenderId: '31364040406',
    projectId: 'flutter-paint-store-app',
    storageBucket: 'flutter-paint-store-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterPaintStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxljftN6XnOqNEqs_qnxnmABr3c6mSqaA',
    appId: '1:31364040406:ios:1fe5b604a793bc00b36b77',
    messagingSenderId: '31364040406',
    projectId: 'flutter-paint-store-app',
    storageBucket: 'flutter-paint-store-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterPaintStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBZ52HCg8vvPcPo4AGGncy4zQ_hMZnQ8g',
    appId: '1:31364040406:web:23568ce9b70f8b43b36b77',
    messagingSenderId: '31364040406',
    projectId: 'flutter-paint-store-app',
    authDomain: 'flutter-paint-store-app.firebaseapp.com',
    storageBucket: 'flutter-paint-store-app.firebasestorage.app',
  );
}
